# Generated by Django 6.0.6 on 2026-06-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answerss',
        ),
    ]
